on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mycoolacr.azurecr.io
        username: ${{ secrets.acr_mycoolacr_username }}
        password: ${{ secrets.acr_mycoolacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t mycoolacr.azurecr.io/mycluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push mycoolacr.azurecr.io/mycluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mycluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mycluster82e2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mycluster82e2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mycluster82e2
        container-registry-url: mycoolacr.azurecr.io
        container-registry-username: ${{ secrets.acr_mycoolacr_username }}
        container-registry-password: ${{ secrets.acr_mycoolacr_password }}
        secret-name: myclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mycluster82e2
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          mycoolacr.azurecr.io/mycluster:${{ github.sha }}
        imagepullsecrets: |
          myclusterdockerauth
